# 1. 初探数据

In [3]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

data_train = pd.read_csv('./input/train.csv')
data_train.head()

,Activity,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,D1767,D1768,D1769,D1770,D1771,D1772,D1773,D1774,D1775,D1776
0,1,0.000000,0.497009,0.10,0.0,0.132956,0.678031,0.273166,0.585445,0.743663,...,0,0,0,0,0,0,0,0,0,0
1,1,0.366667,0.606291,0.05,0.0,0.111209,0.803455,0.106105,0.411754,0.836582,...,1,1,1,1,0,1,0,0,1,0
2,1,0.033300,0.480124,0.00,0.0,0.209791,0.610350,0.356453,0.517720,0.679051,...,0,0,0,0,0,0,0,0,0,0
3,1,0.000000,0.538825,0.00,0.5,0.196344,0.724230,0.235606,0.288764,0.805110,...,0,0,0,0,0,0,0,0,0,0
4,0,0.100000,0.517794,0.00,0.0,0.494734,0.781422,0.154361,0.303809,0.812646,...,0,0,0,0,0,0,0,0,0,0

In [17]:
data_test = pd.read_csv('./input/test.csv')
data_test.head()

,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,...,D1767,D1768,D1769,D1770,D1771,D1772,D1773,D1774,D1775,D1776
0,0.366667,0.611765,0.05,0.0,0.110435,0.803973,0.106075,0.473965,0.835617,0.106452,...,1,1,1,1,0,1,0,0,1,0
1,0.100000,0.758175,0.30,0.0,0.180128,0.621378,0.287144,0.503919,0.674919,0.403616,...,0,0,0,0,0,0,0,0,0,0
2,0.100000,0.658812,0.10,0.0,0.243421,0.640959,0.312765,0.279784,0.686775,0.280301,...,0,0,0,0,0,0,0,0,0,0
3,0.100000,0.655752,0.10,0.0,0.226978,0.776996,0.150657,0.336948,0.802121,0.125608,...,0,0,0,0,0,0,0,0,0,0
4,0.000000,0.484851,0.00,0.0,0.561200,0.771463,0.244287,0.293096,0.717575,0.230842,...,0,0,0,0,0,0,0,0,0,0

我们可以看到，这些数据总共有1777列组成，其中第一列代表是否有生物反应。对于其他类，由于没有给出具体的字段信息，所以我们不知道其他类代表的特征是什么。

In [4]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3751 entries, 0 to 3750
Columns: 1777 entries, Activity to D1776
dtypes: float64(942), int64(835)
memory usage: 50.9 MB

In [5]:
data_train.describe()

,Activity,D1,D2,D3,D4,D5,D6,D7,D8,D9,...,D1767,D1768,D1769,D1770,D1771,D1772,D1773,D1774,D1775,D1776
count,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,...,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000,3751.000000
mean,0.542255,0.076948,0.592436,0.068142,0.038990,0.212112,0.686653,0.274713,0.455133,0.749517,...,0.026926,0.014663,0.013863,0.021861,0.015196,0.016796,0.012263,0.011730,0.020261,0.011197
std,0.498278,0.079989,0.105860,0.078414,0.115885,0.102592,0.078702,0.090017,0.162731,0.071702,...,0.161889,0.120215,0.116938,0.146249,0.122348,0.128522,0.110074,0.107683,0.140911,0.105236
min,0.000000,0.000000,0.282128,0.000000,0.000000,0.002630,0.137873,0.006130,0.000000,0.275590,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.033300,0.517811,0.000000,0.000000,0.138118,0.625627,0.207374,0.378062,0.707339,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.066700,0.585989,0.050000,0.000000,0.190926,0.674037,0.277845,0.499942,0.738961,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,0.100000,0.668395,0.100000,0.000000,0.261726,0.740663,0.335816,0.569962,0.788177,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,0.964381,0.950000,1.000000,1.000000,0.994735,0.790831,0.989870,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

我们通过data_train.describe()来看一下数据的统计信息，这个信息中，我们可以看到，数据似乎是没有缺失的，而且，每一列的值似乎都是在[0,1]之间的。下面我们将读写数据，封装成一个函数，以便后面调用。

In [6]:
# 基本csv读写操作
# 我们需要读取给定的训练数据，再进行后续的数据处理

def read_data(file_name):
    f = open(file_name)
    # ignore header
    f.readline()
    samples = []
    for line in f:
        line = line.strip().split(',')
        sample = [float(x) for x in line]
        samples.append(sample)
    return samples

def write_delimited_file(file_path, data, header=None, delimiter=','):
    f_out = open(file_path, 'w')
    if header is not None:
        f_out.write(delimiter.join(header) + '\n')
    for line in data:
        if isinstance(line, str):
            f_out.write(line + '\n')
        else:
            f_out.write(delimiter.join(line) + '\n')
    f_out.close()

# 2. 建模
我们这里简单的用sklearn中的逻辑回归来训练数据，建立模型，熟悉一下sklearn中的逻辑回归。

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
import math
import scipy

def lr_predict():
    # read in the training file
    train = read_data('./input/train.csv')
    print('读取训练数据完毕')
    # set the training response
    target = [x[0] for x in train]
    #set the training features
    train = [x[1:] for x in train]
    # read in the test file
    realtest = read_data('./input/test.csv')
    print('读取待预测数据')
    
    # code for logistic regression
    lr = LogisticRegression()
    lr.fit(train, target)
    print('Logistic Regression训练完毕!\n...\n')
    predicted_probs = lr.predict_proba(realtest)
    # write solutions to file
    predicted_probs = ['%f' % x[1] for x in predicted_probs]
    write_delimited_file('./output/lr_solution.csv', predicted_probs)
    print('Logistic Regression预测完毕! 请提交lr_solution.csv文件到Kaggle')

    
def svm_predict():
    train = read_data("./input/train.csv")
    print('读取训练数据完毕')
    target = [x[0] for x in train]
    train = [x[1:] for x in train]
    test = read_data("./input/test.csv")
    print('读取待预测数据')
    
    svc = svm.SVC(probability=True)
    svc.fit(train, target)
    print('SVM训练完毕!\n...\n')
    predicted_probs = svc.predict_proba(test)
    predicted_probs = ["%f" % x[1] for x in predicted_probs]
    write_delimited_file("./output/svm_solution.csv",
                                predicted_probs)
    print('SVM预测完毕! 请提交svm_solution.csv文件到Kaggle')
    
if __name__ == '__main__':
    svm_predict()

读取训练数据完毕
读取待预测数据
SVM训练完毕!
...

SVM预测完毕! 请提交svm_solution.csv文件到Kaggle